[unstable]
build-std = ["core", "panic_abort", "compiler_builtins"]
build-std-features = ["optimize_for_size", "compiler-builtins-mem"]

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"
rustflags = [
  "-Ctarget-cpu=cortex-m0plus",
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tlink.x",
  "-Clink-arg=-Tlink-rp.x",
  "-Clink-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = false
lto = true
